/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package savings.tracker;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tabbed_Panel = new javax.swing.JTabbedPane();
        Main = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        Target = new javax.swing.JPanel();
        CheckLabel = new javax.swing.JLabel();
        Target_Check_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Target_Enter_Target_TextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Target_Reset_Button = new javax.swing.JButton();
        Target_OK_Button = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Target_Status_TextArea = new javax.swing.JTextArea();
        Entry = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Day = new javax.swing.JComboBox();
        Month = new javax.swing.JComboBox();
        Year = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Entry_Status_TextArea = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        Entry_Purpose_TextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Entry_Amount_TextField = new javax.swing.JTextField();
        Entry_Reset_Button = new javax.swing.JButton();
        Entry_SaveToExpenses_Button = new javax.swing.JButton();
        Entry_SaveToSavings_Button = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        History = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        History_Button = new javax.swing.JButton();
        History_ScrollPanel = new javax.swing.JScrollPane();
        History_TextArea = new javax.swing.JTextArea();
        Status = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Status_Button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Status_TextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Savings Tracker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(256, 192));

        Tabbed_Panel.setName(""); // NOI18N

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Read the instructions below vey carefully to use this software");

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("This application is all about tracking your savings & expenses:\n1. Set a target safety margin in \"Target\" tab.\n2. Enter your entries (savings/expenses) in \"Entry\" tab.\n3. In \"History\" tab, you can review your added entries.\n4. In \"Status\" tab, you can fnd out your profit or loss.\n\nSpeciality:\n1. All works are done on file, so data loss is not an issue.\n2. This application gives you advice in \"Status\" Tab.\n\nDeveloped in: NetBeans\nVersion: 8.0.2");
        jScrollPane4.setViewportView(jTextArea1);

        javax.swing.GroupLayout MainLayout = new javax.swing.GroupLayout(Main);
        Main.setLayout(MainLayout);
        MainLayout.setHorizontalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        MainLayout.setVerticalGroup(
            MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabbed_Panel.addTab("Main", Main);

        CheckLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        CheckLabel.setText("To check your current safe amount please tap the button beside.");

        Target_Check_Button.setText("Check");
        Target_Check_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Target_Check_ButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter new target safe amount:");

        Target_Enter_Target_TextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setText("Know what's happening:");

        Target_Reset_Button.setText("Reset");
        Target_Reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Target_Reset_ButtonActionPerformed(evt);
            }
        });

        Target_OK_Button.setText("OK");
        Target_OK_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Target_OK_ButtonActionPerformed(evt);
            }
        });

        Target_Status_TextArea.setEditable(false);
        Target_Status_TextArea.setColumns(20);
        Target_Status_TextArea.setLineWrap(true);
        Target_Status_TextArea.setRows(5);
        Target_Status_TextArea.setText("After each event, you can see what just happened in this status area.");
        jScrollPane2.setViewportView(Target_Status_TextArea);

        javax.swing.GroupLayout TargetLayout = new javax.swing.GroupLayout(Target);
        Target.setLayout(TargetLayout);
        TargetLayout.setHorizontalGroup(
            TargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TargetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TargetLayout.createSequentialGroup()
                        .addComponent(CheckLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Target_Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Target_Enter_Target_TextField)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TargetLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Target_OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Target_Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TargetLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        TargetLayout.setVerticalGroup(
            TargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TargetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Target_Check_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Target_Enter_Target_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(TargetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Target_Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Target_OK_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tabbed_Panel.addTab("Target", Target);

        jLabel3.setText("Enter Date of Saving or Expense:");

        Day.setMaximumRowCount(12);
        Day.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Day", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Month.setMaximumRowCount(12);
        Month.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        Year.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Year", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", "2050" }));

        Entry_Status_TextArea.setEditable(false);
        Entry_Status_TextArea.setColumns(20);
        Entry_Status_TextArea.setLineWrap(true);
        Entry_Status_TextArea.setRows(5);
        Entry_Status_TextArea.setText("After each event, you can see what just happened in this status area.");
        jScrollPane1.setViewportView(Entry_Status_TextArea);

        jLabel4.setText("Purpose of Savings or Expenses:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Savings or Expenses Amount:");

        Entry_Reset_Button.setText("Reset");
        Entry_Reset_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entry_Reset_ButtonActionPerformed(evt);
            }
        });

        Entry_SaveToExpenses_Button.setText("Add to Expenses");
        Entry_SaveToExpenses_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entry_SaveToExpenses_ButtonActionPerformed(evt);
            }
        });

        Entry_SaveToSavings_Button.setText("Add to Savings");
        Entry_SaveToSavings_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entry_SaveToSavings_ButtonActionPerformed(evt);
            }
        });

        jLabel6.setText("Know what's happening:");

        javax.swing.GroupLayout EntryLayout = new javax.swing.GroupLayout(Entry);
        Entry.setLayout(EntryLayout);
        EntryLayout.setHorizontalGroup(
            EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(Entry_Purpose_TextField)
                    .addGroup(EntryLayout.createSequentialGroup()
                        .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntryLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntryLayout.createSequentialGroup()
                        .addComponent(Entry_SaveToSavings_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entry_SaveToExpenses_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entry_Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EntryLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entry_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        EntryLayout.setVerticalGroup(
            EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EntryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Day, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(EntryLayout.createSequentialGroup()
                        .addComponent(Entry_Purpose_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Entry_Amount_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Entry_Reset_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EntryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Entry_SaveToExpenses_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Entry_SaveToSavings_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        Tabbed_Panel.addTab("Entry", Entry);

        jLabel7.setText("Tap the button beside to know your Savings and Expenses History.");

        History_Button.setText("Refresh");
        History_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                History_ButtonActionPerformed(evt);
            }
        });

        History_TextArea.setEditable(false);
        History_TextArea.setColumns(20);
        History_TextArea.setLineWrap(true);
        History_TextArea.setRows(5);
        History_ScrollPanel.setViewportView(History_TextArea);

        javax.swing.GroupLayout HistoryLayout = new javax.swing.GroupLayout(History);
        History.setLayout(HistoryLayout);
        HistoryLayout.setHorizontalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(History_ScrollPanel)
                    .addGroup(HistoryLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(History_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        HistoryLayout.setVerticalGroup(
            HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HistoryLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HistoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(History_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(History_ScrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabbed_Panel.addTab("History", History);

        jLabel8.setText("To know your current status please tap the Refresh button.");

        Status_Button.setText("Refresh");
        Status_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Status_ButtonActionPerformed(evt);
            }
        });

        Status_TextArea.setEditable(false);
        Status_TextArea.setColumns(20);
        Status_TextArea.setLineWrap(true);
        Status_TextArea.setRows(5);
        jScrollPane3.setViewportView(Status_TextArea);

        javax.swing.GroupLayout StatusLayout = new javax.swing.GroupLayout(Status);
        Status.setLayout(StatusLayout);
        StatusLayout.setHorizontalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(StatusLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Status_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        StatusLayout.setVerticalGroup(
            StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatusLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(StatusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Status_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                .addContainerGap())
        );

        Tabbed_Panel.addTab("Status", Status);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabbed_Panel)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Tabbed_Panel)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Target_OK_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Target_OK_ButtonActionPerformed
        // TODO add your handling code here:
        String temp;
        temp=Target_Enter_Target_TextField.getText();
        try{
            int new_target_value = Integer.parseInt(temp);
            String file_name = "target.txt";
            try{
                FileWriter fileWriter = new FileWriter(file_name);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                bufferedWriter.write(temp);
                bufferedWriter.close();
                Target_Status_TextArea.setText("Target Amout is set to " + temp + " successfully!");
            } catch (IOException ex) {
                Target_Status_TextArea.setText("Unusual Error! File can't be created!");
            }
        }catch(NumberFormatException e){
            Target_Status_TextArea.setText("Entry is not an amout/integer. Please enter a valid amout/integer.");
        }
    }//GEN-LAST:event_Target_OK_ButtonActionPerformed

    private void Target_Check_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Target_Check_ButtonActionPerformed
        // TODO add your handling code here:
        String File_name = "target.txt";
        String line=null;
        
        try{
            FileReader fileReader = new FileReader(File_name);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            while((line = bufferedReader.readLine())!=null)
            {
                Target_Status_TextArea.setText("Your current safe-margin amount is " +line+ ".");
            }
        } catch(FileNotFoundException ex)  
        {
            Target_Status_TextArea.setText("You have not set any target amout yet!");
        } catch (IOException ex) {
            Target_Status_TextArea.setText("Unusual Error! Something went wrong!");
        }
    }//GEN-LAST:event_Target_Check_ButtonActionPerformed

    private void Target_Reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Target_Reset_ButtonActionPerformed
        // TODO add your handling code here:
        Target_Status_TextArea.setText("After each event, you can see what just happened in this status area.");
        Target_Enter_Target_TextField.setText("");
    }//GEN-LAST:event_Target_Reset_ButtonActionPerformed

    private void Entry_SaveToSavings_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entry_SaveToSavings_ButtonActionPerformed
        // TODO add your handling code here:
        String temp=Entry_Purpose_TextField.getText();
        String problems="";
        int value=0;
        if(Day.getSelectedItem()=="Day")
        {
            problems=problems+"Invalid Day\n";
        }
        if(Month.getSelectedItem()=="Month")
        {
            problems=problems+"Invalid Month\n";
        }
        if(Year.getSelectedItem()=="Year")
        {
            problems=problems+"Invalid Year\n";
        }
        if(temp.isEmpty())
        {
            problems=problems+"Please enter the source of Saving/Expense\n";
        }
        try{
            int value2 = Integer.parseInt(Entry_Amount_TextField.getText());
        }catch(NumberFormatException e){
            problems=problems+"Please enter an integer value in amount area.\n";
        }
        if(problems!="")
        {
            Entry_Status_TextArea.setText(problems);
            problems="";
        }
        else
        {
            String file_name = "status.txt";
            String line=null;
            try{
                FileReader fileReader = new FileReader(file_name);
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                while((line = bufferedReader.readLine())!=null)
                {
                    value=Integer.parseInt(Entry_Amount_TextField.getText())+Integer.parseInt(line);
                }
                bufferedReader.close();
            } catch(FileNotFoundException ex)  
            {
                value=Integer.parseInt(Entry_Amount_TextField.getText());
            } catch (IOException ex) {
                Entry_Status_TextArea.setText("Unusual Error! Something went wrong!");
            }
            
            try{
                FileWriter fileWriter = new FileWriter(file_name);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                bufferedWriter.write(String.valueOf(value));
                bufferedWriter.close();
                Entry_Status_TextArea.setText("Savings added successfully!");
            } catch (IOException ex) {
                Entry_Status_TextArea.setText("Unusual Error! File can't be created!");
            }
            
            String history="";
            file_name="history.txt";
            line=null;
            try{
                FileReader fileReader = new FileReader(file_name);
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                while((line = bufferedReader.readLine())!=null)
                {
                    history=history+line+"\n";
                }
                bufferedReader.close();
            } catch(FileNotFoundException ex)  
            {
                
            } catch (IOException ex) {
                
            }
            history=history+"Savings: "+Day.getSelectedItem()+" "+Month.getSelectedItem()+" "+Year.getSelectedItem()+", "+Entry_Purpose_TextField.getText()+": "+Entry_Amount_TextField.getText()+"\n";
            
            try{
                FileWriter fileWriter = new FileWriter(file_name);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                bufferedWriter.write(history);
                bufferedWriter.close();
            } catch (IOException ex) {
                
            }
        }
    }//GEN-LAST:event_Entry_SaveToSavings_ButtonActionPerformed

    private void Entry_SaveToExpenses_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entry_SaveToExpenses_ButtonActionPerformed
        // TODO add your handling code here:
        String temp=Entry_Purpose_TextField.getText();
        String problems="";
        int value=0;
        if(Day.getSelectedItem()=="Day")
        {
            problems=problems+"Invalid Day\n";
        }
        if(Month.getSelectedItem()=="Month")
        {
            problems=problems+"Invalid Month\n";
        }
        if(Year.getSelectedItem()=="Year")
        {
            problems=problems+"Invalid Year\n";
        }
        if(temp.isEmpty())
        {
            problems=problems+"Please enter the source of Saving/Expense\n";
        }
        try{
            int value2 = Integer.parseInt(Entry_Amount_TextField.getText());
        }catch(NumberFormatException e){
            problems=problems+"Please enter an integer value in amount area.\n";
        }
        if(problems!="")
        {
            Entry_Status_TextArea.setText(problems);
            problems="";
        }
        else
        {
            String file_name = "status.txt";
            String line=null;
            try{
                FileReader fileReader = new FileReader(file_name);
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                while((line = bufferedReader.readLine())!=null)
                {
                    value=Integer.parseInt(line)-Integer.parseInt(Entry_Amount_TextField.getText());
                }
                bufferedReader.close();
            } catch(FileNotFoundException ex)  
            {
                value=-Integer.parseInt(Entry_Amount_TextField.getText());
            } catch (IOException ex) {
                Entry_Status_TextArea.setText("Unusual Error! Something went wrong!");
            }
            
            try{
                FileWriter fileWriter = new FileWriter(file_name);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                bufferedWriter.write(String.valueOf(value));
                bufferedWriter.close();
                Entry_Status_TextArea.setText("Expenses added successfully!");
            } catch (IOException ex) {
                Entry_Status_TextArea.setText("Unusual Error! File can't be created!");
            }
            
            String history="";
            file_name="history.txt";
            line=null;
            try{
                FileReader fileReader = new FileReader(file_name);
                BufferedReader bufferedReader = new BufferedReader(fileReader);
                while((line = bufferedReader.readLine())!=null)
                {
                    history=history+line+"\n";
                }
                bufferedReader.close();
            } catch(FileNotFoundException ex)  
            {
                
            } catch (IOException ex) {
                
            }
            history=history+"Expenses: "+Day.getSelectedItem()+" "+Month.getSelectedItem()+" "+Year.getSelectedItem()+", "+Entry_Purpose_TextField.getText()+": "+Entry_Amount_TextField.getText()+"\n";
            
            try{
                FileWriter fileWriter = new FileWriter(file_name);
                BufferedWriter bufferedWriter = new BufferedWriter(fileWriter);
                bufferedWriter.write(history);
                bufferedWriter.close();
            } catch (IOException ex) {
                
            }
        }
    }//GEN-LAST:event_Entry_SaveToExpenses_ButtonActionPerformed

    private void Entry_Reset_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entry_Reset_ButtonActionPerformed
        // TODO add your handling code here:
        Day.setSelectedItem("Day");
        Month.setSelectedItem("Month");
        Year.setSelectedItem("Year");
        Entry_Purpose_TextField.setText(null);
        Entry_Amount_TextField.setText(null);
        Entry_Status_TextArea.setText("After each event, you can see what just happened in this status area.");
    }//GEN-LAST:event_Entry_Reset_ButtonActionPerformed

    private void History_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_History_ButtonActionPerformed
        // TODO add your handling code here:
        String history="";
        String file_name = "history.txt";
        String line = null;
        try {
            FileReader fileReader = new FileReader(file_name);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            while ((line = bufferedReader.readLine()) != null) {
                history = line + "\n" + history;
            }
            bufferedReader.close();
        } catch (FileNotFoundException ex) {
            history = "No history available...";
        } catch (IOException ex) {

        }
        History_TextArea.setText(history);
    }//GEN-LAST:event_History_ButtonActionPerformed

    private void Status_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Status_ButtonActionPerformed
        // TODO add your handling code here:
        String check="";
        String text=null;
        int target=0, status=0;
        String file_name = "target.txt";
        String line = null;
        try {
            FileReader fileReader = new FileReader(file_name);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            while ((line = bufferedReader.readLine()) != null) {
                check=line;
            }
            bufferedReader.close();
            target=Integer.parseInt(check);
            text="Your safety margin is " + target + "\n";
        } catch (FileNotFoundException ex) {
            text="You haven't set your target.\n";
        } catch (IOException ex) {

        }
        
        file_name="status.txt";
        line = null;
        try {
            FileReader fileReader = new FileReader(file_name);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            while ((line = bufferedReader.readLine()) != null) {
                check=line;
            }
            bufferedReader.close();
            status=Integer.parseInt(check);
            if(text!="You haven't set your target.\n")
            {
                text=text+"You are going on ";
                if(status<0){
                    text=text+(-1)*status+" taka loss. :(";
                }
                else if(status>0){
                    text=text+status+" taka profit. ^_^";
                }
                else{
                    text=text+"neither in profit nor in loss. O.o";
                }
                text=text+"\nYour status is "+status+"\n";
                if(target<status){
                    text=text+"Well done! You can go to restuarent! ;)";
                }
                else if(target>status){
                    text=text+"Come on! You're expending much. Stop right now! -_-";
                }
                else{
                    text=text+"Okay! I've nothing to sey. You're on the safety margin. :)";
                }
            }
            else
            {
                text=text+"You do not have any entries yet. But I can tell you this:\n";
                text=text+"You are going on ";
                if(status<0){
                    text=text+(-1)*status+" taka loss. :(";
                }
                else if(status>0){
                    text=text+status+" taka profit. ^_^";
                }
                else{
                    text=text+"You're neither in profit nor in loss. O.o";
                }
                text=text+"\nYour status is "+status;
            }
        } catch (FileNotFoundException ex) {
                text=text+"You do not have any entries yet.";
        } catch (IOException ex) {

        }
        Status_TextArea.setText(text);
    }//GEN-LAST:event_Status_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CheckLabel;
    private javax.swing.JComboBox Day;
    private javax.swing.JPanel Entry;
    private javax.swing.JTextField Entry_Amount_TextField;
    private javax.swing.JTextField Entry_Purpose_TextField;
    private javax.swing.JButton Entry_Reset_Button;
    private javax.swing.JButton Entry_SaveToExpenses_Button;
    private javax.swing.JButton Entry_SaveToSavings_Button;
    private javax.swing.JTextArea Entry_Status_TextArea;
    private javax.swing.JPanel History;
    private javax.swing.JButton History_Button;
    private javax.swing.JScrollPane History_ScrollPanel;
    private javax.swing.JTextArea History_TextArea;
    private javax.swing.JPanel Main;
    private javax.swing.JComboBox Month;
    private javax.swing.JPanel Status;
    private javax.swing.JButton Status_Button;
    private javax.swing.JTextArea Status_TextArea;
    private javax.swing.JTabbedPane Tabbed_Panel;
    private javax.swing.JPanel Target;
    private javax.swing.JButton Target_Check_Button;
    private javax.swing.JTextField Target_Enter_Target_TextField;
    private javax.swing.JButton Target_OK_Button;
    private javax.swing.JButton Target_Reset_Button;
    private javax.swing.JTextArea Target_Status_TextArea;
    private javax.swing.JComboBox Year;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
